apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-gc
  labels:
    app: k8s-gc
spec:
  selector:
    matchLabels:
      name: k8s-gc
  template:
    metadata:
      labels:
        name: k8s-gc
    spec:
      containers:
      - name: k8s-gc
        image: heltondd/k8s-gc
        env:
          - name: INTERVAL
            value: "86400"
          - name: UNTIL
            value: "24h"
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
          readOnly: false
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock